import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import type { Account } from "../interfaces";

import Link from "next/link";
import {
  WalletSelectorContextProvider,
  useWalletSelector,
} from "../contexts/WalletSelectorContext";

import { api } from "../utils/api";
import SignIn from "../components/SignIn";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <WalletSelectorContextProvider>
          <h1 className="text-4xl font-bold text-white">Welcome to T3!</h1>
          <SignIn />
        </WalletSelectorContextProvider>
      </main>
    </>
  );
};

export default Home;
